# render.yaml
services:
  - type: web
    name: medusa-store
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 9000
      - key: REDIS_URL
        fromService:
          name: medusa-redis
          type: redis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STORE_CORS
        value: https://your-store-domain.com
      - key: ADMIN_CORS
        value: https://your-admin-domain.com

  - type: redis
    name: medusa-redis
    ipAllowList: []
    plan: free

databases:
  - name: medusa-db
    databaseName: medusa
    user: medusa
    plan: free
